"""데이터베이스 테이블 스키마 정의"""

TABLES = {
    'projects': """
        CREATE TABLE PROJECTS (
            ID INTEGER NOT NULL PRIMARY KEY,
            NAME VARCHAR(100) NOT NULL,
            PATH VARCHAR(500),
            DESCRIPTION BLOB SUB_TYPE TEXT,
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """,
    
    'sequences': """
        CREATE TABLE SEQUENCES (
            ID INTEGER NOT NULL PRIMARY KEY,
            NAME VARCHAR(100) NOT NULL,
            PROJECT_ID INTEGER NOT NULL,
            DESCRIPTION BLOB SUB_TYPE TEXT,
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(ID) ON DELETE CASCADE
        )
    """,
    
    'shots': """
        CREATE TABLE SHOTS (
            ID INTEGER NOT NULL PRIMARY KEY,
            NAME VARCHAR(100) NOT NULL,
            SEQUENCE_ID INTEGER NOT NULL,
            STATUS VARCHAR(20) DEFAULT 'pending',
            DESCRIPTION BLOB SUB_TYPE TEXT,
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (SEQUENCE_ID) REFERENCES SEQUENCES(ID) ON DELETE CASCADE
        )
    """,
    
    'versions': """
        CREATE TABLE VERSIONS (
            ID INTEGER NOT NULL PRIMARY KEY,
            NAME VARCHAR(100) NOT NULL,
            SHOT_ID INTEGER NOT NULL,
            VERSION_NUMBER INTEGER NOT NULL,
            WORKER_ID INTEGER,
            STATUS VARCHAR(50) DEFAULT 'pending',
            FILE_PATH VARCHAR(500),
            PREVIEW_PATH VARCHAR(500),
            RENDER_PATH VARCHAR(500),
            COMMENT VARCHAR(500),
            IS_LATEST BOOLEAN DEFAULT TRUE,
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            PATH VARCHAR(500),
            FOREIGN KEY (SHOT_ID) REFERENCES SHOTS(ID) ON DELETE CASCADE,
            FOREIGN KEY (WORKER_ID) REFERENCES WORKERS(ID)
        )
    """,

    'workers': """
        CREATE TABLE WORKERS (
            ID INTEGER NOT NULL PRIMARY KEY,
            NAME VARCHAR(100) NOT NULL,
            DEPARTMENT VARCHAR(50),
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """,
    
    'settings': """
        CREATE TABLE SETTINGS (
            SETTING_KEY VARCHAR(100) NOT NULL PRIMARY KEY,
            SETTING_VALUE VARCHAR(500) NOT NULL,
            DESCRIPTION BLOB SUB_TYPE 1,
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """
}